name: Node.js CI

on:
  push:
    branches: [ main, feature-langchain ]
  pull_request:
    branches: [ main, feature-langchain ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    # Install and test frontend
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client

    - name: Test frontend
      run: npm test
      working-directory: ./client
      env:
        CI: true
        VITE_KINDE_CONNECTION_EMAIL_PASSWORD: mock_connection_id
        VITE_KINDE_CONNECTION_GOOGLE: mock_google_connection_id
        VITE_KINDE_CONNECTION_FACEBOOK: mock_facebook_connection_id

    # Install and test backend
    - name: Install backend dependencies
      run: npm ci
      working-directory: ./backend

    - name: Test backend
      run: npm test
      working-directory: ./backend
      env:
        CI: true
