name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    # Install and test frontend
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client

    - name: Test frontend
      run: npm test
      working-directory: ./client
      env:
        CI: true
