name: Node.js CI

on:
  push:
    branches: [ main, test-setup ]
  pull_request:
    branches: [ main, test-setup ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    # Install and test backend
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install backend dependencies
      run: npm ci
      working-directory: ./backend

    - name: Test backend
      run: npm test
      working-directory: ./backend
      env:
        CI: true

    # Install and test frontend
    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./client

    - name: Test frontend
      run: npm test
      working-directory: ./client
      env:
        CI: true
